name: Validate Spec

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: validate
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli validate -i /local/Building/swagger.yaml